llm:
  type: openrouter
  models:
    openrouter: "qwen/qwen-2.5-72b-instruct"
    openai: Null
    anthropic: Null
  api_keys:
    openrouter: "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"
    openai: ""
    anthropic: ""
  temperature: 0.7

benchmark:
  checkpoint: "checkpoints"
  verbose: true
  output_pattern: "results/{dataset_name}_{model}.json"